### ISSUE TITLE
Simple api for swipeleft/swiperight

### ISSUE THREAD

**Issue by naveedahmed1** [aGoncharuks/angular-swipe-directive#2]
Here's a suggestion to add simple api for swipeleft/swiperight.

Please also publish it on npm, I think this directive could be an alternative for applications that requires simple swipe gestured but have to rely on hammerjs.

**Comment by aGoncharuks** [comment]
@naveedahmed1 please find published library on npm https://www.npmjs.com/package/ng-swipe.

I'm not a big fan of adding additional event emitters. All four swipe directions can be easily detected by filtering events by events 'direction' and 'distance' fields in consumer component e.g. right swipe will have direction 'x' and positive distance.

**Comment by naveedahmed1** [comment]
Awesome! Thank you so much @aGoncharuks :)
