### ISSUE TITLE
Listener blocks normal scrolling.

### ISSUE THREAD

**Issue by jkyoutsey** [aGoncharuks/angular-swipe-directive#3]
I have a simple div with ngSwipe on it and both listeners.
I have my detection handling left and right swipes.
But, how do I allow up and down to propagate up so that scrolling happens if needed? Currently, if I try to scroll up or down with a touch on that div it won't scroll.

**Comment by aGoncharuks** [comment]
@jkyoutsey I will take a look

**Comment by jkyoutsey** [comment]
Any luck on this? I'm using this component in a lot of places and it's a major problem that I cannot scroll. It's affecting desktop and mobile both.

**Comment by jkyoutsey** [comment]
I found it. It's not your code. The problem was with the div having overflow-x: hidden.  It needed overflow: hidden. I'm closing this.
